name: golangci-lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    strategy:
      fail-fast: true
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --disable-all -E deadcode, errcheck, gosimple, govet, ineffassign, staticcheck, typecheck, unused, varcheck, bidichk, cyclop, decorder, depguard, dogsled, dupl, durationcheck, errchkjson, errname, errorlint, exportloopref, gci, gocognit, goconst, gocyclo, godox, goerr113, goimports, gomnd, goprintffuncname, gosec, grouper, ifshort, maintidx, makezero, nakedret, nilerr, nilnil, nlreturn, nosnakecase, prealloc, predeclared, revive, unconvert, unparam, wastedassign, whitespace
